const fs = require("fs");
const https = require("https");
const express = require("express");

const app = express();
const path = require("path");

// Zertifikate - Pfade anpassen falls nötig
const options = {
  key: fs.readFileSync("server.key"),
  cert: fs.readFileSync("server.crt"),
  requestCert: true,
  rejectUnauthorized: true,
  ca: fs.readFileSync("ca.crt"),
  minVersion: "TLSv1.2", // Wichtig für macOS Kompatibilität
  ciphers: ["ECDHE-ECDSA-AES256-GCM-SHA384", "ECDHE-RSA-AES256-GCM-SHA384"].join(":"),
};

// Middleware für Client-Zertifikat
app.use((req, res, next) => {
  if (!req.client.authorized) {
    console.log("Unauthorized client:", req.client.authorizationError);
    return res.status(403).end();
  }
  next();
});

app.get("/", (req, res) => {
  res.type("text/plain").sendFile(path.join(__dirname, "format.html"));
});

app.get("/index", (req, res) => {
  res.sendFile(path.join(__dirname, "index.html"));
});

app.get("/sh/solar/opendtu", (req, res) => {
  const solarData = {
    total: {
      Power: { v: 123.56, u: "W" },
      YieldDay: { v: 3.2, u: "kWh" },
      YieldTotal: { v: 1245.8, u: "kWh" },
    },
  };
  res.json(solarData);
});

app.get("/sh/visu/heizung/ajax/read_table_vicare_latest", (req, res) => {
  const data = [
    {
      Temp_Aussen: "7.4",
      timestamp: "27.03.2025 11:30",
      Modus: "Auto",
      Brenner_Betriebsstunden: "1234",
      Brenner_Starts: "40",
    },
  ];
  res.json(data);
});

app.get("/knx/ajax/knx_read_ga", (req, res) => {
  const { ga, DPT, Type, ID, Name, bfname, age } = req.query;

 
  // Dummy-Rückgabe je nach Type
  let value0 = "1"; // geschlossen
  let value1 = "err" || "Unbenannt";

  if (Type === "F" && Name?.toLowerCase().includes("badfenster")) {
    console.log("📥 Anfrage erhalten:");
    console.log("GA:", ga, "| DPT:", DPT, "| Type:", Type, "| ID:", ID, "| Name:", Name.toLowerCase(), "| bfname:", bfname, "| age:", age);
    value0 = "0";
    console.log("📤 Antwort:", [value0, value1]);
  }

  if (Type === "F" && Name?.toLowerCase() == "flur eg fenster") {
    value0 = "1";
  }

  if(Name?.toLowerCase() == "strom leistung") {
    value1 = "1001";
  }

  if (Type === "T" && Name?.toLowerCase().includes("haustuere")) {
    value0 = "0";
  }

  res.json([value0, value1]);
});

app.get("/knx/ajax/knx_read_temp_lfh", (req, res) => {
  const { ga1, ga2, ga3, ID, age } = req.query;

  // Dummy: Temperatur + Luftfeuchtigkeit
  res.json(["22.5", "15"]);
});

app.get("/devices", (req, res) => {
  const deviceList = [
    [
      "K",
      "Bad",
      "Arcus",
      "7/2/1;9/2/1;9/2/4",
      "",
      "BADTempLFH",
      "TLFH",
      "60",
      "",
      "",
      "",
      "",
      "30",
      "0",
      "0",
      "5",
      "Bathroom",
    ],
    [
      "K",
      "Bad",
      "Lingg",
      "7/2/3;9/2/2",
      "",
      "BADTempLFH2",
      "TLFH",
      "60",
      "",
      "",
      "",
      "",
      "0",
      "0",
      "0",
      "6",
      "Bathroom",
    ],
    [
      "K",
      "Bad",
      "MDT Bad",
      "7/2/2",
      "9.001",
      "BADTemp2",
      "Temp",
      "120",
      "",
      "",
      "",
      "",
      "0",
      "0",
      "0",
      "7",
      "Bathroom",
    ],
    [
      "K",
      "Bad",
      "Badfenster",
      "1/0/7;1/0/8",
      "1.019",
      "BADFD",
      "F",
      "0",
      "",
      "",
      "",
      "",
      "0",
      "1",
      "0",
      "8",
      "Bathroom",
    ],
    [
      "K",
      "Bad",
      "Rollladen Bad",
      "2/2/9",
      "5.001",
      "BADR",
      "R",
      "120",
      "",
      "2/1/14",
      "",
      "",
      "0",
      "0",
      "0",
      "9",
      "Bathroom",
    ],
    [
      "K",
      "Bad",
      "Bad Hauptlicht mA",
      "10/1/2",
      "7.012",
      "B_HL_mA",
      "",
      "120",
      "",
      "",
      "",
      "",
      "0",
      "0",
      "0",
      "10",
      "Bathroom",
    ],
    [
      "K",
      "Bad",
      "Bad Hauptlicht h",
      "10/3/2",
      "7.007",
      "B_HL_OPSH",
      "",
      "120",
      "",
      "",
      "",
      "",
      "0",
      "0",
      "0",
      "11",
      "Bathroom",
    ],
    [
      "K",
      "Bad",
      "Bad Hauptlicht kWh",
      "10/2/2",
      "13.010",
      "B_HL_KWH",
      "",
      "120",
      "",
      "",
      "",
      "",
      "0",
      "0",
      "0",
      "12",
      "Bathroom",
    ],
    [
      "K",
      "Bad",
      "Hauptlicht Bad",
      "3/1/2",
      "1.011",
      "B_HL",
      "S",
      "0",
      "bad_hl",
      "",
      "",
      "",
      "0",
      "1",
      "0",
      "13",
      "Bathroom",
    ],
    [
      "K",
      "Bad",
      "Bad Duschlicht mA",
      "10/1/3",
      "7.012",
      "B_DL_mA",
      "",
      "120",
      "",
      "",
      "",
      "",
      "0",
      "0",
      "0",
      "14",
      "Bathroom",
    ],
    [
      "K",
      "Bad",
      "Bad Duschlicht h",
      "10/3/3",
      "7.007",
      "B_DL_OPSH",
      "",
      "120",
      "",
      "",
      "",
      "",
      "0",
      "0",
      "0",
      "16",
      "Bathroom",
    ],
    [
      "K",
      "Bad",
      "Bad Duschlicht kWh",
      "10/2/3",
      "13.010",
      "B_DL_KWH",
      "",
      "120",
      "",
      "",
      "",
      "",
      "0",
      "0",
      "0",
      "17",
      "Bathroom",
    ],
    [
      "K",
      "Bad",
      "Duschlicht Bad",
      "3/1/3",
      "1.011",
      "B_DL",
      "S",
      "0",
      "bad_dl",
      "",
      "",
      "",
      "0",
      "1",
      "0",
      "18",
      "Bathroom",
    ],
    ["K", "Bad", "Bad HTW", "3/1/4", "1.011", "B_HW", "S", "0", "bad_hw", "", "", "", "0", "1", "0", "19", "Bathroom"],
    [
      "K",
      "Bad",
      "Bad Handtuchwärmer mA",
      "10/1/4",
      "7.012",
      "B_HW_mA",
      "",
      "120",
      "",
      "",
      "",
      "",
      "0",
      "0",
      "0",
      "20",
      "Bathroom",
    ],
    [
      "K",
      "Bad",
      "Bad Handtuchwärmer h",
      "10/3/4",
      "7.007",
      "B_HW_OPSH",
      "",
      "120",
      "",
      "",
      "",
      "",
      "0",
      "0",
      "0",
      "21",
      "Bathroom",
    ],
    [
      "K",
      "Bad",
      "Bad Handtuchwärmer kWh",
      "10/2/4",
      "13.013",
      "B_HW_KWH",
      "",
      "120",
      "",
      "",
      "",
      "",
      "0",
      "0",
      "0",
      "22",
      "Bathroom",
    ],
    [
      "F",
      "Büro Oben",
      "Thermostat Büro",
      "13979 0233132",
      "",
      "BCHTemp2",
      "Temp",
      "",
      "",
      "",
      "",
      "",
      "0",
      "0",
      "0",
      "1",
      "Office",
    ],
    ["K", "Büro Oben", "", "", "", "BCHR", "R", "120", "", "", "", "", "0", "0", "0", "50", "Office"],
    ["K", "Büro Oben", "", "", "1.019", "BCHBLKT", "T", "0", "", "", "", "", "0", "1", "0", "51", "Office"],
    [
      "K",
      "Büro Oben",
      "Büro Oben MDT",
      "7/0/0",
      "9.001",
      "BCHTemp",
      "Temp",
      "120",
      "",
      "",
      "",
      "",
      "30",
      "0",
      "0",
      "52",
      "Office",
    ],
    [
      "K",
      "Büro Unten",
      "Büro Chris Temperatur",
      "7/1/3",
      "9.001",
      "EG_BCTemp",
      "Temp",
      "120",
      "",
      "",
      "",
      "",
      "0",
      "0",
      "0",
      "73",
      "Office",
    ],
    [
      "K",
      "Büro Unten",
      "Büro Chris Fenster",
      "1/0/20;1/0/21",
      "1.019",
      "EG_BCF",
      "F",
      "0",
      "",
      "",
      "",
      "",
      "0",
      "1",
      "0",
      "74",
      "Office",
    ],
    [
      "K",
      "Büro Unten",
      "Büro Chris",
      "2/2/7",
      "5.001",
      "EG_BCR",
      "R",
      "120",
      "",
      "2/1/17",
      "",
      "",
      "0",
      "0",
      "0",
      "75",
      "Office",
    ],
    [
      "D",
      "Flur EG",
      "",
      "192.168.0.208",
      "",
      "FLUR_NL",
      "S",
      "",
      "flur_licht",
      "",
      "",
      "",
      "0",
      "0",
      "0",
      "4",
      "Hallway",
    ],
    [
      "K",
      "Flur EG",
      "Eingang Temperatur",
      "7/1/0",
      "9.001",
      "EingangTemp",
      "Temp",
      "120",
      "",
      "",
      "",
      "",
      "30",
      "0",
      "0",
      "59",
      "Hallway",
    ],
    [
      "K",
      "Flur EG",
      "Flur EG Fenster",
      "1/0/12",
      "1.019",
      "EingangFenster",
      "F",
      "0",
      "",
      "",
      "",
      "",
      "0",
      "1",
      "0",
      "60",
      "Hallway",
    ],
    [
      "K",
      "Flur EG",
      "Rollladen Flur EG",
      "2/2/0",
      "5.001",
      "EingangR",
      "R",
      "120",
      "",
      "2/1/2",
      "",
      "",
      "0",
      "0",
      "0",
      "61",
      "Hallway",
    ],
    [
      "K",
      "Flur EG",
      "Haustuere",
      "1/0/13",
      "1.019",
      "EingangTR1;EingangT",
      "T",
      "0",
      "",
      "",
      "0",
      "http://gheihk0003:kwnSrej9NW@doorbird.fritz.box/bha-api/sip.cgi?action=hangup",
      "0",
      "1",
      "0",
      "62",
      "Hallway",
    ],
    [
      "K",
      "Flur EG",
      "Haustürriegel",
      "1/0/14",
      "1.019",
      "EingangTR2",
      "V",
      "0",
      "",
      "",
      "",
      "",
      "0",
      "1",
      "0",
      "63",
      "Hallway",
    ],
    [
      "K",
      "Flur OG",
      "Fenster Flur OG",
      "1/0/4;1/0/5",
      "1.019",
      "OGFF",
      "F",
      "0",
      "",
      "",
      "",
      "",
      "0",
      "1",
      "0",
      "49",
      "Hallway",
    ],
    ["K", "Garten", "", "10/3/6", "7.007", "Garten_S1_OPSH", "", "120", "", "", "", "", "0", "0", "0", "140", "Garden"],
    ["K", "Garten", "", "10/3/7", "7.007", "Garten_S2_OPSH", "", "120", "", "", "", "", "0", "0", "0", "141", "Garden"],
    ["K", "Garten", "", "10/2/6", "13.010", "Garten_S1_KWH", "", "120", "", "", "", "", "0", "0", "0", "142", "Garden"],
    ["K", "Garten", "", "10/2/7", "13.010", "Garten_S2_KWH", "", "120", "", "", "", "", "0", "0", "0", "143", "Garden"],
    [
      "K",
      "Garten",
      "GartenDose2",
      "3/1/7",
      "1.011",
      "GartenDose2",
      "S",
      "60",
      "schuko",
      "",
      "",
      "",
      "0",
      "1",
      "0",
      "55",
      "Garden",
    ],
    [
      "K",
      "Garten",
      "GartenDose1",
      "3/1/6",
      "1.011",
      "GartenDose1",
      "S",
      "60",
      "schuko",
      "",
      "",
      "",
      "0",
      "1",
      "0",
      "56",
      "Garden",
    ],
    [
      "K",
      "Garten",
      "",
      "10/1/6",
      "7.012",
      "GartenSchuko1_mA",
      "",
      "120",
      "",
      "",
      "",
      "",
      "0",
      "0",
      "0",
      "115",
      "Garden",
    ],
    [
      "K",
      "Garten",
      "",
      "10/1/7",
      "7.012",
      "GartenSchuko2_mA",
      "",
      "120",
      "",
      "",
      "",
      "",
      "0",
      "0",
      "0",
      "116",
      "Garden",
    ],
    [
      "K",
      "Hobby",
      "Arcus Hobbyraum",
      "7/3/0;9/3/0;9/3/1",
      "",
      "HB_TempLFH",
      "TLFH",
      "60",
      "",
      "",
      "",
      "",
      "0",
      "0",
      "0",
      "25",
      "Hobby Room",
    ],
    [
      "K",
      "Hobby",
      "Hobbyraum Fenster",
      "1/0/22;1/0/23",
      "1.019",
      "HB_F",
      "F",
      "0",
      "",
      "",
      "",
      "",
      "0",
      "1",
      "0",
      "26",
      "Hobby Room",
    ],
    [
      "K",
      "Hobby",
      "Arcus Hobbyraum",
      "10/0/0",
      "9.008",
      "HB_VOC",
      "VOC",
      "120",
      "",
      "",
      "",
      "",
      "0",
      "0",
      "0",
      "27",
      "Hobby Room",
    ],
    [
      "K",
      "HWR",
      "HWR Temperatur",
      "7/2/4",
      "9.001",
      "HWRTemp",
      "Temp",
      "",
      "",
      "",
      "",
      "",
      "0",
      "0",
      "0",
      "46",
      "Utility Room",
    ],
    [
      "K",
      "HWR",
      "Fenster HWR",
      "1/0/6",
      "1.019",
      "HWRF",
      "F",
      "0",
      "",
      "",
      "",
      "",
      "0",
      "1",
      "0",
      "47",
      "Utility Room",
    ],
    [
      "K",
      "HWR",
      "Rollladen HWR",
      "2/2/8",
      "5.001",
      "HWR_R",
      "R",
      "120",
      "",
      "2/1/20",
      "",
      "",
      "0",
      "0",
      "0",
      "48",
      "Utility Room",
    ],
    [
      "K",
      "Julia",
      "Julia Fenster R",
      "1/0/27",
      "1.019",
      "JULIA_F",
      "F",
      "60",
      "",
      "",
      "",
      "",
      "0",
      "1",
      "1",
      "113",
      "Bedroom",
    ],
    ["K", "Keller Links", "", "", "9.001", "KL_GS", "S", "0", "", "", "", "", "0", "1", "0", "78", "Cellar"],
    [
      "K",
      "Keller Rechts",
      "Panzerriegel Keller",
      "1/0/24",
      "1.019",
      "KR_PR",
      "PR",
      "0",
      "",
      "",
      "",
      "",
      "0",
      "1",
      "0",
      "76",
      "Cellar",
    ],
    [
      "K",
      "Keller Rechts",
      "Keller Rechts Fenster",
      "1/0/25",
      "1.019",
      "KR_F",
      "F",
      "0",
      "",
      "",
      "",
      "",
      "0",
      "1",
      "0",
      "77",
      "Cellar",
    ],
    [
      "K",
      "kl. Bad",
      "Arcus kl. Bad",
      "7/2/0;9/2/0;9/2/3",
      "",
      "KLBADTEMPLFH",
      "TLFH",
      "60",
      "",
      "",
      "",
      "",
      "30",
      "0",
      "0",
      "23",
      "Small Bathroom",
    ],
    [
      "K",
      "kl. Bad",
      "kl. Bad Fenster",
      "1/0/3",
      "1.019",
      "KLBADF",
      "F",
      "60",
      "",
      "",
      "",
      "",
      "0",
      "1",
      "0",
      "24",
      "Small Bathroom",
    ],
    [
      "K",
      "Küche",
      "Lingg Küche zu WZ",
      "7/1/2;9/1/0",
      "",
      "K_TempLFH",
      "TLFH",
      "60",
      "",
      "",
      "",
      "",
      "30",
      "0",
      "0",
      "28",
      "Kitchen",
    ],
    [
      "K",
      "Küche",
      "Lingg Küche zu Flur",
      "7/1/4;9/1/1",
      "",
      "K_TempLFH2",
      "TLFH",
      "60",
      "",
      "",
      "",
      "",
      "0",
      "0",
      "0",
      "29",
      "Kitchen",
    ],
    [
      "K",
      "Küche",
      "MDT Küche",
      "7/1/1",
      "9.001",
      "K_Temp3",
      "Temp",
      "120",
      "",
      "",
      "",
      "",
      "0",
      "0",
      "0",
      "30",
      "Kitchen",
    ],
    [
      "K",
      "Küche",
      "Küche Fenster",
      "1/0/15;1/0/16",
      "1.019",
      "K_F",
      "F",
      "0",
      "",
      "",
      "",
      "",
      "0",
      "1",
      "0",
      "31",
      "Kitchen",
    ],
    [
      "K",
      "Küche",
      "Küche Hauptlicht mA",
      "10/1/0",
      "7.012",
      "K_HL_mA",
      "",
      "120",
      "",
      "",
      "",
      "",
      "0",
      "0",
      "0",
      "32",
      "Kitchen",
    ],
    [
      "K",
      "Küche",
      "Küche Hauptlicht h",
      "10/3/0",
      "7.007",
      "K_HL_OPSH",
      "",
      "120",
      "",
      "",
      "",
      "",
      "0",
      "0",
      "0",
      "33",
      "Kitchen",
    ],
    [
      "K",
      "Küche",
      "Küche Hauptlicht kWh",
      "10/2/0",
      "13.010",
      "K_HL_KWH",
      "",
      "120",
      "",
      "",
      "",
      "",
      "0",
      "0",
      "0",
      "34",
      "Kitchen",
    ],
    [
      "K",
      "Küche",
      "Küche Nebenlicht mA",
      "10/1/1",
      "7.012",
      "K_NL_mA",
      "",
      "120",
      "",
      "",
      "",
      "",
      "0",
      "0",
      "0",
      "35",
      "Kitchen",
    ],
    [
      "K",
      "Küche",
      "Küche Nebenlicht h",
      "10/3/1",
      "7.007",
      "K_NL_OPSH",
      "",
      "120",
      "",
      "",
      "",
      "",
      "0",
      "0",
      "0",
      "36",
      "Kitchen",
    ],
    [
      "K",
      "Küche",
      "Küche Nebenlicht kWh",
      "10/2/1",
      "13.010",
      "K_NL_KWH",
      "",
      "120",
      "",
      "",
      "",
      "",
      "0",
      "0",
      "0",
      "37",
      "Kitchen",
    ],
    [
      "K",
      "Küche",
      "Rollladen Küche",
      "2/2/1",
      "5.001",
      "K_R",
      "R",
      "120",
      "",
      "2/1/5",
      "",
      "",
      "0",
      "0",
      "0",
      "38",
      "Kitchen",
    ],
    [
      "K",
      "Küche",
      "Küche Hauptlicht",
      "3/1/0",
      "1.011",
      "K_HL",
      "S",
      "0",
      "k_hl",
      "",
      "",
      "",
      "0",
      "1",
      "0",
      "39",
      "Kitchen",
    ],
    [
      "K",
      "Küche",
      "Küche Nebenlicht",
      "3/1/1",
      "1.011",
      "K_NL",
      "S",
      "0",
      "k_nl",
      "",
      "",
      "",
      "0",
      "1",
      "0",
      "40",
      "Kitchen",
    ],
    [
      "K",
      "Ölraum",
      "Ölraum Fenster",
      "1/0/26",
      "1.019",
      "OEL_F",
      "F",
      "600",
      "",
      "",
      "",
      "",
      "0",
      "1",
      "0",
      "79",
      "Oil Room",
    ],
    [
      "F",
      "Schlafzimmer",
      "Thermostat Schlafzimmer",
      "13979 0238667",
      "",
      "DG_SZTemp",
      "Temp",
      "",
      "",
      "",
      "",
      "",
      "0",
      "0",
      "0",
      "2",
      "Bedroom",
    ],
    [
      "K",
      "Schlafzimmer",
      "Schlafzimmer Fenster R",
      "1/0/2",
      "1.019",
      "DG_SZF",
      "F",
      "60",
      "",
      "",
      "",
      "",
      "0",
      "1",
      "1",
      "110",
      "Bedroom",
    ],
    [
      "K",
      "Schlafzimmer",
      "Schlafzimmer Fenster L",
      "1/0/1",
      "1.019",
      "DG_SZFL",
      "F",
      "60",
      "",
      "",
      "",
      "",
      "0",
      "1",
      "1",
      "131",
      "Bedroom",
    ],
    [
      "K",
      "Sophie",
      "Sophie Fenster R",
      "1/0/29",
      "1.019",
      "SOPHIE_F",
      "F",
      "60",
      "",
      "",
      "",
      "",
      "0",
      "1",
      "1",
      "114",
      "Bedroom",
    ],
    [
      "K",
      "Spielzimmer",
      "Licht Spielzimmer",
      "3/1/5",
      "1.011",
      "SZLI",
      "S",
      "0",
      "sz_l",
      "",
      "",
      "",
      "0",
      "1",
      "0",
      "0",
      "Playroom",
    ],
    [
      "K",
      "Spielzimmer",
      "MDT",
      "7/2/5",
      "9.001",
      "SZTemp",
      "Temp",
      "120",
      "",
      "",
      "",
      "",
      "0",
      "0",
      "0",
      "41",
      "Playroom",
    ],
    [
      "K",
      "Spielzimmer",
      "Spielzimmer Links",
      "1/0/9",
      "1.019",
      "SZFL",
      "F",
      "60",
      "",
      "",
      "",
      "",
      "0",
      "1",
      "0",
      "42",
      "Playroom",
    ],
    [
      "K",
      "Spielzimmer",
      "Spielzimmer Mitte",
      "1/0/10",
      "1.019",
      "SZFM",
      "F",
      "60",
      "",
      "",
      "",
      "",
      "0",
      "1",
      "0",
      "43",
      "Playroom",
    ],
    [
      "K",
      "Spielzimmer",
      "Spielzimmer Rechts",
      "1/0/11",
      "1.019",
      "SZFR",
      "F",
      "60",
      "",
      "",
      "",
      "",
      "0",
      "1",
      "0",
      "44",
      "Playroom",
    ],
    [
      "K",
      "Spielzimmer",
      "Rollladen Spielzimmer",
      "2/2/10",
      "5.001",
      "SZR",
      "R",
      "120",
      "",
      "2/1/23",
      "",
      "",
      "0",
      "0",
      "0",
      "45",
      "Playroom",
    ],
    [
      "K",
      "Spielzimmer",
      "Spielzimmer Lampe h",
      "10/3/5",
      "7.007",
      "SZ_L_OPSH",
      "",
      "120",
      "",
      "",
      "",
      "",
      "0",
      "0",
      "0",
      "111",
      "Playroom",
    ],
    [
      "K",
      "Spielzimmer",
      "Spielzimmer Lampe kWh",
      "10/2/5",
      "13.010",
      "SZ_L_KWH",
      "",
      "120",
      "",
      "",
      "",
      "",
      "0",
      "0",
      "0",
      "117",
      "Playroom",
    ],
    [
      "K",
      "Spielzimmer",
      "Spielzimmer Licht mA",
      "10/1/5",
      "7.012",
      "SZ_L_mA",
      "",
      "120",
      "",
      "",
      "",
      "",
      "0",
      "0",
      "0",
      "220",
      "Playroom",
    ],
    [
      "K",
      "Strom",
      "Strom Leistung",
      "0/1/1",
      "14.056",
      "StromP",
      "W",
      "120",
      "",
      "",
      "",
      "",
      "0",
      "0",
      "0",
      "57",
      "Electricity",
    ],
    [
      "K",
      "Strom",
      "Stromzählerstand kWh",
      "0/1/0",
      "13.013",
      "StromKWH",
      "KWH",
      "120",
      "",
      "",
      "",
      "",
      "0",
      "0",
      "0",
      "58",
      "Electricity",
    ],
    [
      "K",
      "Strom",
      "Strom Leistung Lieferun",
      "0/1/3",
      "14.056",
      "StromPL",
      "W",
      "120",
      "",
      "",
      "",
      "",
      "0",
      "0",
      "0",
      "257",
      "Electricity",
    ],
    [
      "K",
      "Strom",
      "Stromzählerstand kWh Li",
      "0/1/4",
      "13.013",
      "StromKWHL",
      "KWH",
      "120",
      "",
      "",
      "",
      "",
      "0",
      "0",
      "0",
      "258",
      "Electricity",
    ],
    [
      "D",
      "Wohnzimmer",
      "",
      "192.168.0.205",
      "",
      "WZ_NL",
      "S",
      "",
      "wz_licht",
      "",
      "",
      "",
      "0",
      "0",
      "0",
      "3",
      "Living Room",
    ],
    [
      "K",
      "Wohnzimmer",
      "Wohnzimmer Temperatur",
      "7/1/5",
      "9.001",
      "WZ_Temp",
      "Temp",
      "120",
      "",
      "",
      "",
      "",
      "0",
      "0",
      "0",
      "64",
      "Living Room",
    ],
    ["K", "Wohnzimmer", "", "", "9.001", "WZ_F2", "S", "0", "", "", "", "", "0", "1", "0", "65", "Living Room"],
    [
      "K",
      "Wohnzimmer",
      "WZ F3",
      "1/0/18",
      "1.019",
      "WZ_F3",
      "F",
      "0",
      "",
      "",
      "",
      "",
      "0",
      "1",
      "0",
      "66",
      "Living Room",
    ],
    [
      "K",
      "Wohnzimmer",
      "Terassentür",
      "1/0/17",
      "1.019",
      "WZ_F5",
      "T",
      "0",
      "",
      "",
      "",
      "",
      "0",
      "1",
      "0",
      "67",
      "Living Room",
    ],
    ["K", "Wohnzimmer", "", "", "5.001", "WZ_R1", "R", "120", "", "", "", "", "0", "0", "0", "68", "Living Room"],
    ["K", "Wohnzimmer", "", "", "5.001", "WZ_R2", "R", "120", "", "", "", "", "0", "0", "0", "69", "Living Room"],
    [
      "K",
      "Wohnzimmer",
      "Rollladen WZ F3",
      "2/2/4",
      "5.001",
      "WZ_R3",
      "R",
      "120",
      "",
      "2/1/31",
      "",
      "",
      "0",
      "0",
      "0",
      "70",
      "Living Room",
    ],
    [
      "K",
      "Wohnzimmer",
      "Rollladen WZ 4",
      "2/2/3",
      "5.001",
      "WZ_R4",
      "R",
      "120",
      "",
      "2/1/11",
      "",
      "",
      "0",
      "0",
      "0",
      "71",
      "Living Room",
    ],
    [
      "K",
      "Wohnzimmer",
      "Rollladen WZ 5",
      "2/2/2",
      "5.001",
      "WZ_R5",
      "R",
      "120",
      "",
      "2/1/8",
      "",
      "",
      "0",
      "0",
      "0",
      "72",
      "Living Room",
    ],
  ];

  res.json(deviceList);
});

const server = https.createServer(options, app);

// macOS-spezifische Socket-Einstellungen
server.listen(3000, "0.0.0.0", () => {
  // Nicht nur localhost
  console.log("Server läuft auf https://0.0.0.0:3000");
});

// Keep-Alive für CLI-Tools
server.keepAliveTimeout = 30000;
